language: php

php:
    - 7.0
    - 7.1
    - nightly

env:
    - COMPOSERFLAGS=
    - COMPOSERFLAGS=--prefer-lowest

matrix:
    exclude:
        - php: 7.0
          env: COMPOSERFLAGS=
        - php: 7.1
          env: COMPOSERFLAGS=--prefer-lowest
        - php: nightly
          env: COMPOSERFLAGS=--prefer-lowest
    allow_failures:
        - php: nightly

script:
    - make test
